<!doctype html>
<html lang="pt-BR" prefix="og: http://ogp.me/ns#" prefix="og: https://ogp.me/ns#" class="no-js">
<head>
    <meta charset="UTF-8" />

    <link rel="profile" href="http://gmpg.org/xfn/11" />
    <link rel="stylesheet" type="text/css" media="all" href="https://www.mutua.com.br/wp-content/themes/mutua/style.css" />
    <link rel="stylesheet" type="text/css" media="all" href="https://www.mutua.com.br/wp-content/themes/mutua/assets/css/site.css" />
    <link rel="pingback" href="https://www.mutua.com.br/xmlrpc.php" />
    <link href="https://www.mutua.com.br/wp-content/themes/mutua/assets/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Material+Icons+Round" rel="stylesheet">

    <script type="text/javascript">
        window.onload = (event) => {

            let botaoBusca = document.querySelector("#botao-busca");
            let containerBusca = document.querySelector(".container-busca");
            botaoBusca.addEventListener("click", function() {
                containerBusca.classList.toggle("d-none");
            });

        };

    </script>

    <!-- Google Tag Manager -->
    <script>
        (function(w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start': new Date().getTime()
                , event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0]
                , j = d.createElement(s)
                , dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-5RGTBZK');

    </script>
    <!-- End Google Tag Manager -->

    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5RGTBZK" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-BGHTVEG9T2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-BGHTVEG9T2');

    </script>
    <!-- Tags generated by Easy Social Share Buttons for WordPress v8.7 - https://socialsharingplugin.com. You see this message only because you have debug mode ON -->
    <meta property="og:locale" content="pt_BR" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Mútua+Azul" />
    <meta property="og:url" content="https://www.mutua.com.br/beneficios/mutuamaisazul/" />
    <meta property="og:site_name" content="MÚTUA" />

    <!-- Otimização de mecanismos de pesquisa por Rank Math - https://rankmath.com/ -->
    <title>@yield('title') - MÚTUA</title>
    <meta name="robots" content="follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large" />
    <link rel="canonical" href="https://www.mutua.com.br/beneficios/mutuamaisazul/" />
    <meta property="og:locale" content="pt_BR" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Mútua+Azul - MÚTUA" />
    <meta property="og:url" content="https://www.mutua.com.br/beneficios/mutuamaisazul/" />
    <meta property="og:site_name" content="MÚTUA" />
    <meta property="og:updated_time" content="2023-07-10T14:25:34-03:00" />
    <meta property="article:published_time" content="2023-07-10T08:52:40-03:00" />
    <meta property="article:modified_time" content="2023-07-10T14:25:34-03:00" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="Mútua+Azul - MÚTUA" />
    <meta name="twitter:label1" content="Tempo de leitura" />
    <meta name="twitter:data1" content="Menos de um minuto" />
    <script type="application/ld+json" class="rank-math-schema">
        {
            "@context": "https://schema.org"
            , "@graph": [{
                "@type": ["Person", "Organization"]
                , "@id": "https://www.mutua.com.br/#person"
                , "name": "DEFAULT"
            }, {
                "@type": "WebSite"
                , "@id": "https://www.mutua.com.br/#website"
                , "url": "https://www.mutua.com.br"
                , "name": "M\u00daTUA"
                , "publisher": {
                    "@id": "https://www.mutua.com.br/#person"
                }
                , "inLanguage": "pt-BR"
            }, {
                "@type": "WebPage"
                , "@id": "https://www.mutua.com.br/beneficios/mutuamaisazul/#webpage"
                , "url": "https://www.mutua.com.br/beneficios/mutuamaisazul/"
                , "name": "M\u00fatua+Azul - M\u00daTUA"
                , "datePublished": "2023-07-10T08:52:40-03:00"
                , "dateModified": "2023-07-10T14:25:34-03:00"
                , "isPartOf": {
                    "@id": "https://www.mutua.com.br/#website"
                }
                , "inLanguage": "pt-BR"
            }, {
                "@type": "Person"
                , "@id": "https://www.mutua.com.br/author/suporte/"
                , "name": "suporte"
                , "url": "https://www.mutua.com.br/author/suporte/"
                , "image": {
                    "@type": "ImageObject"
                    , "@id": "https://secure.gravatar.com/avatar/f1515fc49eefae9bef1d534544fea879?s=96&amp;d=mm&amp;r=g"
                    , "url": "https://secure.gravatar.com/avatar/f1515fc49eefae9bef1d534544fea879?s=96&amp;d=mm&amp;r=g"
                    , "caption": "suporte"
                    , "inLanguage": "pt-BR"
                }
                , "sameAs": ["https://www.mutua.com.br"]
            }, {
                "@type": "Article"
                , "headline": "M\u00fatua+Azul - M\u00daTUA"
                , "datePublished": "2023-07-10T08:52:40-03:00"
                , "dateModified": "2023-07-10T14:25:34-03:00"
                , "author": {
                    "@id": "https://www.mutua.com.br/author/suporte/"
                    , "name": "suporte"
                }
                , "publisher": {
                    "@id": "https://www.mutua.com.br/#person"
                }
                , "name": "M\u00fatua+Azul - M\u00daTUA"
                , "@id": "https://www.mutua.com.br/beneficios/mutuamaisazul/#richSnippet"
                , "isPartOf": {
                    "@id": "https://www.mutua.com.br/beneficios/mutuamaisazul/#webpage"
                }
                , "inLanguage": "pt-BR"
                , "mainEntityOfPage": {
                    "@id": "https://www.mutua.com.br/beneficios/mutuamaisazul/#webpage"
                }
            }]
        }

    </script>
    <!-- /Plugin de SEO do Rank Math para WordPress -->

    <link rel='dns-prefetch' href='//www.mutua.com.br' />
    <link rel='dns-prefetch' href='//cdnjs.cloudflare.com' />
    <link rel='dns-prefetch' href='//stackpath.bootstrapcdn.com' />
    <link rel='dns-prefetch' href='//fonts.googleapis.com' />
    <link rel='dns-prefetch' href='//cdn.jsdelivr.net' />
    <style id='wp-block-library-theme-inline-css' type='text/css'>
        .wp-block-audio figcaption {
            color: #555;
            font-size: 13px;
            text-align: center
        }

        .is-dark-theme .wp-block-audio figcaption {
            color: hsla(0, 0%, 100%, .65)
        }

        .wp-block-audio {
            margin: 0 0 1em
        }

        .wp-block-code {
            border: 1px solid #ccc;
            border-radius: 4px;
            font-family: Menlo, Consolas, monaco, monospace;
            padding: .8em 1em
        }

        .wp-block-embed figcaption {
            color: #555;
            font-size: 13px;
            text-align: center
        }

        .is-dark-theme .wp-block-embed figcaption {
            color: hsla(0, 0%, 100%, .65)
        }

        .wp-block-embed {
            margin: 0 0 1em
        }

        .blocks-gallery-caption {
            color: #555;
            font-size: 13px;
            text-align: center
        }

        .is-dark-theme .blocks-gallery-caption {
            color: hsla(0, 0%, 100%, .65)
        }

        .wp-block-image figcaption {
            color: #555;
            font-size: 13px;
            text-align: center
        }

        .is-dark-theme .wp-block-image figcaption {
            color: hsla(0, 0%, 100%, .65)
        }

        .wp-block-image {
            margin: 0 0 1em
        }

        .wp-block-pullquote {
            border-bottom: 4px solid;
            border-top: 4px solid;
            color: currentColor;
            margin-bottom: 1.75em
        }

        .wp-block-pullquote cite,
        .wp-block-pullquote footer,
        .wp-block-pullquote__citation {
            color: currentColor;
            font-size: .8125em;
            font-style: normal;
            text-transform: uppercase
        }

        .wp-block-quote {
            border-left: .25em solid;
            margin: 0 0 1.75em;
            padding-left: 1em
        }

        .wp-block-quote cite,
        .wp-block-quote footer {
            color: currentColor;
            font-size: .8125em;
            font-style: normal;
            position: relative
        }

        .wp-block-quote.has-text-align-right {
            border-left: none;
            border-right: .25em solid;
            padding-left: 0;
            padding-right: 1em
        }

        .wp-block-quote.has-text-align-center {
            border: none;
            padding-left: 0
        }

        .wp-block-quote.is-large,
        .wp-block-quote.is-style-large,
        .wp-block-quote.is-style-plain {
            border: none
        }

        .wp-block-search .wp-block-search__label {
            font-weight: 700
        }

        .wp-block-search__button {
            border: 1px solid #ccc;
            padding: .375em .625em
        }

        :where(.wp-block-group.has-background) {
            padding: 1.25em 2.375em
        }

        .wp-block-separator.has-css-opacity {
            opacity: .4
        }

        .wp-block-separator {
            border: none;
            border-bottom: 2px solid;
            margin-left: auto;
            margin-right: auto
        }

        .wp-block-separator.has-alpha-channel-opacity {
            opacity: 1
        }

        .wp-block-separator:not(.is-style-wide):not(.is-style-dots) {
            width: 100px
        }

        .wp-block-separator.has-background:not(.is-style-dots) {
            border-bottom: none;
            height: 1px
        }

        .wp-block-separator.has-background:not(.is-style-wide):not(.is-style-dots) {
            height: 2px
        }

        .wp-block-table {
            margin: 0 0 1em
        }

        .wp-block-table td,
        .wp-block-table th {
            word-break: normal
        }

        .wp-block-table figcaption {
            color: #555;
            font-size: 13px;
            text-align: center
        }

        .is-dark-theme .wp-block-table figcaption {
            color: hsla(0, 0%, 100%, .65)
        }

        .wp-block-video figcaption {
            color: #555;
            font-size: 13px;
            text-align: center
        }

        .is-dark-theme .wp-block-video figcaption {
            color: hsla(0, 0%, 100%, .65)
        }

        .wp-block-video {
            margin: 0 0 1em
        }

        .wp-block-template-part.has-background {
            margin-bottom: 0;
            margin-top: 0;
            padding: 1.25em 2.375em
        }

    </style>
    <link rel='stylesheet' id='wp-components-css' href='https://www.mutua.com.br/wp-includes/css/dist/components/style.min.css?ver=6.3.1' type='text/css' media='all' />
    <link rel='stylesheet' id='wp-block-editor-css' href='https://www.mutua.com.br/wp-includes/css/dist/block-editor/style.min.css?ver=6.3.1' type='text/css' media='all' />
    <link rel='stylesheet' id='wp-reusable-blocks-css' href='https://www.mutua.com.br/wp-includes/css/dist/reusable-blocks/style.min.css?ver=6.3.1' type='text/css' media='all' />
    <link rel='stylesheet' id='wp-editor-css' href='https://www.mutua.com.br/wp-includes/css/dist/editor/style.min.css?ver=6.3.1' type='text/css' media='all' />
    <link rel='stylesheet' id='sjb_shortcode_block-cgb-style-css-css' href='https://www.mutua.com.br/wp-content/plugins/simple-job-board/sjb-block/dist/blocks.style.build.css' type='text/css' media='all' />
    <style id='classic-theme-styles-inline-css' type='text/css'>
        /*! This file is auto-generated */
        .wp-block-button__link {
            color: #fff;
            background-color: #32373c;
            border-radius: 9999px;
            box-shadow: none;
            text-decoration: none;
            padding: calc(.667em + 2px) calc(1.333em + 2px);
            font-size: 1.125em
        }

        .wp-block-file__button {
            background: #32373c;
            color: #fff;
            text-decoration: none
        }

    </style>
    <style id='global-styles-inline-css' type='text/css'>
        body {
            --wp--preset--color--black: #000000;
            --wp--preset--color--cyan-bluish-gray: #abb8c3;
            --wp--preset--color--white: #ffffff;
            --wp--preset--color--pale-pink: #f78da7;
            --wp--preset--color--vivid-red: #cf2e2e;
            --wp--preset--color--luminous-vivid-orange: #ff6900;
            --wp--preset--color--luminous-vivid-amber: #fcb900;
            --wp--preset--color--light-green-cyan: #7bdcb5;
            --wp--preset--color--vivid-green-cyan: #00d084;
            --wp--preset--color--pale-cyan-blue: #8ed1fc;
            --wp--preset--color--vivid-cyan-blue: #0693e3;
            --wp--preset--color--vivid-purple: #9b51e0;
            --wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(135deg, rgba(6, 147, 227, 1) 0%, rgb(155, 81, 224) 100%);
            --wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(135deg, rgb(122, 220, 180) 0%, rgb(0, 208, 130) 100%);
            --wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(135deg, rgba(252, 185, 0, 1) 0%, rgba(255, 105, 0, 1) 100%);
            --wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(135deg, rgba(255, 105, 0, 1) 0%, rgb(207, 46, 46) 100%);
            --wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(135deg, rgb(238, 238, 238) 0%, rgb(169, 184, 195) 100%);
            --wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(135deg, rgb(74, 234, 220) 0%, rgb(151, 120, 209) 20%, rgb(207, 42, 186) 40%, rgb(238, 44, 130) 60%, rgb(251, 105, 98) 80%, rgb(254, 248, 76) 100%);
            --wp--preset--gradient--blush-light-purple: linear-gradient(135deg, rgb(255, 206, 236) 0%, rgb(152, 150, 240) 100%);
            --wp--preset--gradient--blush-bordeaux: linear-gradient(135deg, rgb(254, 205, 165) 0%, rgb(254, 45, 45) 50%, rgb(107, 0, 62) 100%);
            --wp--preset--gradient--luminous-dusk: linear-gradient(135deg, rgb(255, 203, 112) 0%, rgb(199, 81, 192) 50%, rgb(65, 88, 208) 100%);
            --wp--preset--gradient--pale-ocean: linear-gradient(135deg, rgb(255, 245, 203) 0%, rgb(182, 227, 212) 50%, rgb(51, 167, 181) 100%);
            --wp--preset--gradient--electric-grass: linear-gradient(135deg, rgb(202, 248, 128) 0%, rgb(113, 206, 126) 100%);
            --wp--preset--gradient--midnight: linear-gradient(135deg, rgb(2, 3, 129) 0%, rgb(40, 116, 252) 100%);
            --wp--preset--font-size--small: 13px;
            --wp--preset--font-size--medium: 20px;
            --wp--preset--font-size--large: 36px;
            --wp--preset--font-size--x-large: 42px;
            --wp--preset--spacing--20: 0.44rem;
            --wp--preset--spacing--30: 0.67rem;
            --wp--preset--spacing--40: 1rem;
            --wp--preset--spacing--50: 1.5rem;
            --wp--preset--spacing--60: 2.25rem;
            --wp--preset--spacing--70: 3.38rem;
            --wp--preset--spacing--80: 5.06rem;
            --wp--preset--shadow--natural: 6px 6px 9px rgba(0, 0, 0, 0.2);
            --wp--preset--shadow--deep: 12px 12px 50px rgba(0, 0, 0, 0.4);
            --wp--preset--shadow--sharp: 6px 6px 0px rgba(0, 0, 0, 0.2);
            --wp--preset--shadow--outlined: 6px 6px 0px -3px rgba(255, 255, 255, 1), 6px 6px rgba(0, 0, 0, 1);
            --wp--preset--shadow--crisp: 6px 6px 0px rgba(0, 0, 0, 1);
        }

        :where(.is-layout-flex) {
            gap: 0.5em;
        }

        :where(.is-layout-grid) {
            gap: 0.5em;
        }

        body .is-layout-flow>.alignleft {
            float: left;
            margin-inline-start: 0;
            margin-inline-end: 2em;
        }

        body .is-layout-flow>.alignright {
            float: right;
            margin-inline-start: 2em;
            margin-inline-end: 0;
        }

        body .is-layout-flow>.aligncenter {
            margin-left: auto !important;
            margin-right: auto !important;
        }

        body .is-layout-constrained>.alignleft {
            float: left;
            margin-inline-start: 0;
            margin-inline-end: 2em;
        }

        body .is-layout-constrained>.alignright {
            float: right;
            margin-inline-start: 2em;
            margin-inline-end: 0;
        }

        body .is-layout-constrained>.aligncenter {
            margin-left: auto !important;
            margin-right: auto !important;
        }

        body .is-layout-constrained> :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
            max-width: var(--wp--style--global--content-size);
            margin-left: auto !important;
            margin-right: auto !important;
        }

        body .is-layout-constrained>.alignwide {
            max-width: var(--wp--style--global--wide-size);
        }

        body .is-layout-flex {
            display: flex;
        }

        body .is-layout-flex {
            flex-wrap: wrap;
            align-items: center;
        }

        body .is-layout-flex>* {
            margin: 0;
        }

        body .is-layout-grid {
            display: grid;
        }

        body .is-layout-grid>* {
            margin: 0;
        }

        :where(.wp-block-columns.is-layout-flex) {
            gap: 2em;
        }

        :where(.wp-block-columns.is-layout-grid) {
            gap: 2em;
        }

        :where(.wp-block-post-template.is-layout-flex) {
            gap: 1.25em;
        }

        :where(.wp-block-post-template.is-layout-grid) {
            gap: 1.25em;
        }

        .has-black-color {
            color: var(--wp--preset--color--black) !important;
        }

        .has-cyan-bluish-gray-color {
            color: var(--wp--preset--color--cyan-bluish-gray) !important;
        }

        .has-white-color {
            color: var(--wp--preset--color--white) !important;
        }

        .has-pale-pink-color {
            color: var(--wp--preset--color--pale-pink) !important;
        }

        .has-vivid-red-color {
            color: var(--wp--preset--color--vivid-red) !important;
        }

        .has-luminous-vivid-orange-color {
            color: var(--wp--preset--color--luminous-vivid-orange) !important;
        }

        .has-luminous-vivid-amber-color {
            color: var(--wp--preset--color--luminous-vivid-amber) !important;
        }

        .has-light-green-cyan-color {
            color: var(--wp--preset--color--light-green-cyan) !important;
        }

        .has-vivid-green-cyan-color {
            color: var(--wp--preset--color--vivid-green-cyan) !important;
        }

        .has-pale-cyan-blue-color {
            color: var(--wp--preset--color--pale-cyan-blue) !important;
        }

        .has-vivid-cyan-blue-color {
            color: var(--wp--preset--color--vivid-cyan-blue) !important;
        }

        .has-vivid-purple-color {
            color: var(--wp--preset--color--vivid-purple) !important;
        }

        .has-black-background-color {
            background-color: var(--wp--preset--color--black) !important;
        }

        .has-cyan-bluish-gray-background-color {
            background-color: var(--wp--preset--color--cyan-bluish-gray) !important;
        }

        .has-white-background-color {
            background-color: var(--wp--preset--color--white) !important;
        }

        .has-pale-pink-background-color {
            background-color: var(--wp--preset--color--pale-pink) !important;
        }

        .has-vivid-red-background-color {
            background-color: var(--wp--preset--color--vivid-red) !important;
        }

        .has-luminous-vivid-orange-background-color {
            background-color: var(--wp--preset--color--luminous-vivid-orange) !important;
        }

        .has-luminous-vivid-amber-background-color {
            background-color: var(--wp--preset--color--luminous-vivid-amber) !important;
        }

        .has-light-green-cyan-background-color {
            background-color: var(--wp--preset--color--light-green-cyan) !important;
        }

        .has-vivid-green-cyan-background-color {
            background-color: var(--wp--preset--color--vivid-green-cyan) !important;
        }

        .has-pale-cyan-blue-background-color {
            background-color: var(--wp--preset--color--pale-cyan-blue) !important;
        }

        .has-vivid-cyan-blue-background-color {
            background-color: var(--wp--preset--color--vivid-cyan-blue) !important;
        }

        .has-vivid-purple-background-color {
            background-color: var(--wp--preset--color--vivid-purple) !important;
        }

        .has-black-border-color {
            border-color: var(--wp--preset--color--black) !important;
        }

        .has-cyan-bluish-gray-border-color {
            border-color: var(--wp--preset--color--cyan-bluish-gray) !important;
        }

        .has-white-border-color {
            border-color: var(--wp--preset--color--white) !important;
        }

        .has-pale-pink-border-color {
            border-color: var(--wp--preset--color--pale-pink) !important;
        }

        .has-vivid-red-border-color {
            border-color: var(--wp--preset--color--vivid-red) !important;
        }

        .has-luminous-vivid-orange-border-color {
            border-color: var(--wp--preset--color--luminous-vivid-orange) !important;
        }

        .has-luminous-vivid-amber-border-color {
            border-color: var(--wp--preset--color--luminous-vivid-amber) !important;
        }

        .has-light-green-cyan-border-color {
            border-color: var(--wp--preset--color--light-green-cyan) !important;
        }

        .has-vivid-green-cyan-border-color {
            border-color: var(--wp--preset--color--vivid-green-cyan) !important;
        }

        .has-pale-cyan-blue-border-color {
            border-color: var(--wp--preset--color--pale-cyan-blue) !important;
        }

        .has-vivid-cyan-blue-border-color {
            border-color: var(--wp--preset--color--vivid-cyan-blue) !important;
        }

        .has-vivid-purple-border-color {
            border-color: var(--wp--preset--color--vivid-purple) !important;
        }

        .has-vivid-cyan-blue-to-vivid-purple-gradient-background {
            background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important;
        }

        .has-light-green-cyan-to-vivid-green-cyan-gradient-background {
            background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important;
        }

        .has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background {
            background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important;
        }

        .has-luminous-vivid-orange-to-vivid-red-gradient-background {
            background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important;
        }

        .has-very-light-gray-to-cyan-bluish-gray-gradient-background {
            background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important;
        }

        .has-cool-to-warm-spectrum-gradient-background {
            background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important;
        }

        .has-blush-light-purple-gradient-background {
            background: var(--wp--preset--gradient--blush-light-purple) !important;
        }

        .has-blush-bordeaux-gradient-background {
            background: var(--wp--preset--gradient--blush-bordeaux) !important;
        }

        .has-luminous-dusk-gradient-background {
            background: var(--wp--preset--gradient--luminous-dusk) !important;
        }

        .has-pale-ocean-gradient-background {
            background: var(--wp--preset--gradient--pale-ocean) !important;
        }

        .has-electric-grass-gradient-background {
            background: var(--wp--preset--gradient--electric-grass) !important;
        }

        .has-midnight-gradient-background {
            background: var(--wp--preset--gradient--midnight) !important;
        }

        .has-small-font-size {
            font-size: var(--wp--preset--font-size--small) !important;
        }

        .has-medium-font-size {
            font-size: var(--wp--preset--font-size--medium) !important;
        }

        .has-large-font-size {
            font-size: var(--wp--preset--font-size--large) !important;
        }

        .has-x-large-font-size {
            font-size: var(--wp--preset--font-size--x-large) !important;
        }

        .wp-block-navigation a:where(:not(.wp-element-button)) {
            color: inherit;
        }

        :where(.wp-block-post-template.is-layout-flex) {
            gap: 1.25em;
        }

        :where(.wp-block-post-template.is-layout-grid) {
            gap: 1.25em;
        }

        :where(.wp-block-columns.is-layout-flex) {
            gap: 2em;
        }

        :where(.wp-block-columns.is-layout-grid) {
            gap: 2em;
        }

        .wp-block-pullquote {
            font-size: 1.5em;
            line-height: 1.6;
        }

    </style>
    <link rel='stylesheet' id='contact-form-7-css' href='https://www.mutua.com.br/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=5.8' type='text/css' media='all' />
    <link rel='stylesheet' id='mutua-card-css' href='https://www.mutua.com.br/wp-content/plugins/mutua-card/public/css/mutua-card-public.css?ver=1.0.0' type='text/css' media='all' />
    <link rel='stylesheet' id='simple-job-board-google-fonts-css' href='https://fonts.googleapis.com/css?family=Roboto%3A100%2C100i%2C300%2C300i%2C400%2C400i%2C500%2C500i%2C700%2C700i%2C900%2C900i&#038;ver=2.10.5' type='text/css' media='all' />
    <link rel='stylesheet' id='sjb-fontawesome-css' href='https://www.mutua.com.br/wp-content/plugins/simple-job-board/includes/css/font-awesome.min.css?ver=5.15.4' type='text/css' media='all' />
    <link rel='stylesheet' id='simple-job-board-jquery-ui-css' href='https://www.mutua.com.br/wp-content/plugins/simple-job-board/public/css/jquery-ui.css?ver=1.12.1' type='text/css' media='all' />
    <link rel='stylesheet' id='simple-job-board-frontend-css' href='https://www.mutua.com.br/wp-content/plugins/simple-job-board/public/css/simple-job-board-public.css?ver=3.0.0' type='text/css' media='all' />
    <link rel='stylesheet' id='wp-pagenavi-css' href='https://www.mutua.com.br/wp-content/plugins/wp-pagenavi/pagenavi-css.css?ver=2.70' type='text/css' media='all' />
    <link rel='stylesheet' id='fancybox-css' href='//cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.css?ver=6.3.1' type='text/css' media='all' />
    <link rel='stylesheet' id='subscribe-forms-css-css' href='https://www.mutua.com.br/wp-content/plugins/easy-social-share-buttons3/assets/modules/subscribe-forms.min.css?ver=8.7' type='text/css' media='all' />
    <link rel='stylesheet' id='easy-social-share-buttons-css' href='https://www.mutua.com.br/wp-content/plugins/easy-social-share-buttons3/assets/css/easy-social-share-buttons.min.css?ver=8.7' type='text/css' media='all' />
    <link rel='stylesheet' id='popup-maker-site-css' href='https://www.mutua.com.br/wp-content/plugins/popup-maker/assets/css/pum-site.min.css?ver=1.18.2' type='text/css' media='all' />
    <style id='popup-maker-site-inline-css' type='text/css'>
        /* Popup Google Fonts */
        @import url('//fonts.googleapis.com/css?family=Montserrat:100');

        /* Popup Theme 28784: Light Box */
        .pum-theme-28784,
        .pum-theme-lightbox {
            background-color: rgba(0, 0, 0, 0.60)
        }

        .pum-theme-28784 .pum-container,
        .pum-theme-lightbox .pum-container {
            padding: 18px;
            border-radius: 3px;
            border: 1px solid #000000;
            box-shadow: 0px 0px 30px 0px rgba(2, 2, 2, 1.00);
            background-color: rgba(255, 255, 255, 1.00)
        }

        .pum-theme-28784 .pum-title,
        .pum-theme-lightbox .pum-title {
            color: #000000;
            text-align: left;
            text-shadow: 0px 0px 0px rgba(2, 2, 2, 0.23);
            font-family: inherit;
            font-weight: 100;
            font-size: 20px;
            line-height: 36px
        }

        .pum-theme-28784 .pum-content,
        .pum-theme-lightbox .pum-content {
            color: #000000;
            font-family: inherit;
            font-weight: 100
        }

        .pum-theme-28784 .pum-content+.pum-close,
        .pum-theme-lightbox .pum-content+.pum-close {
            position: absolute;
            height: 26px;
            width: 26px;
            left: auto;
            right: -13px;
            bottom: auto;
            top: -13px;
            padding: 0px;
            color: #ffffff;
            font-family: Arial;
            font-weight: 100;
            font-size: 24px;
            line-height: 24px;
            border: 2px solid #ffffff;
            border-radius: 26px;
            box-shadow: 0px 0px 15px 1px rgba(2, 2, 2, 0.75);
            text-shadow: 0px 0px 0px rgba(0, 0, 0, 0.23);
            background-color: rgba(0, 0, 0, 1.00)
        }

        /* Popup Theme 28783: Default Theme */
        .pum-theme-28783,
        .pum-theme-default-theme {
            background-color: rgba(255, 255, 255, 1.00)
        }

        .pum-theme-28783 .pum-container,
        .pum-theme-default-theme .pum-container {
            padding: 18px;
            border-radius: 0px;
            border: 1px none #000000;
            box-shadow: 1px 1px 3px 0px rgba(2, 2, 2, 0.23);
            background-color: rgba(249, 249, 249, 1.00)
        }

        .pum-theme-28783 .pum-title,
        .pum-theme-default-theme .pum-title {
            color: #000000;
            text-align: left;
            text-shadow: 0px 0px 0px rgba(2, 2, 2, 0.23);
            font-family: inherit;
            font-weight: 400;
            font-size: 32px;
            font-style: normal;
            line-height: 36px
        }

        .pum-theme-28783 .pum-content,
        .pum-theme-default-theme .pum-content {
            color: #8c8c8c;
            font-family: inherit;
            font-weight: 400;
            font-style: inherit
        }

        .pum-theme-28783 .pum-content+.pum-close,
        .pum-theme-default-theme .pum-content+.pum-close {
            position: absolute;
            height: auto;
            width: auto;
            left: auto;
            right: 0px;
            bottom: auto;
            top: 0px;
            padding: 8px;
            color: #ffffff;
            font-family: inherit;
            font-weight: 400;
            font-size: 12px;
            font-style: inherit;
            line-height: 36px;
            border: 1px none #ffffff;
            border-radius: 0px;
            box-shadow: 1px 1px 3px 0px rgba(2, 2, 2, 0.23);
            text-shadow: 0px 0px 0px rgba(0, 0, 0, 0.23);
            background-color: rgba(0, 183, 205, 1.00)
        }

        /* Popup Theme 28785: Enterprise Blue */
        .pum-theme-28785,
        .pum-theme-enterprise-blue {
            background-color: rgba(0, 0, 0, 0.70)
        }

        .pum-theme-28785 .pum-container,
        .pum-theme-enterprise-blue .pum-container {
            padding: 28px;
            border-radius: 5px;
            border: 1px none #000000;
            box-shadow: 0px 10px 25px 4px rgba(2, 2, 2, 0.50);
            background-color: rgba(255, 255, 255, 1.00)
        }

        .pum-theme-28785 .pum-title,
        .pum-theme-enterprise-blue .pum-title {
            color: #315b7c;
            text-align: left;
            text-shadow: 0px 0px 0px rgba(2, 2, 2, 0.23);
            font-family: inherit;
            font-weight: 100;
            font-size: 34px;
            line-height: 36px
        }

        .pum-theme-28785 .pum-content,
        .pum-theme-enterprise-blue .pum-content {
            color: #2d2d2d;
            font-family: inherit;
            font-weight: 100
        }

        .pum-theme-28785 .pum-content+.pum-close,
        .pum-theme-enterprise-blue .pum-content+.pum-close {
            position: absolute;
            height: 28px;
            width: 28px;
            left: auto;
            right: 8px;
            bottom: auto;
            top: 8px;
            padding: 4px;
            color: #ffffff;
            font-family: Times New Roman;
            font-weight: 100;
            font-size: 20px;
            line-height: 20px;
            border: 1px none #ffffff;
            border-radius: 42px;
            box-shadow: 0px 0px 0px 0px rgba(2, 2, 2, 0.23);
            text-shadow: 0px 0px 0px rgba(0, 0, 0, 0.23);
            background-color: rgba(49, 91, 124, 1.00)
        }

        /* Popup Theme 28786: Hello Box */
        .pum-theme-28786,
        .pum-theme-hello-box {
            background-color: rgba(0, 0, 0, 0.75)
        }

        .pum-theme-28786 .pum-container,
        .pum-theme-hello-box .pum-container {
            padding: 30px;
            border-radius: 80px;
            border: 14px solid #81d742;
            box-shadow: 0px 0px 0px 0px rgba(2, 2, 2, 0.00);
            background-color: rgba(255, 255, 255, 1.00)
        }

        .pum-theme-28786 .pum-title,
        .pum-theme-hello-box .pum-title {
            color: #2d2d2d;
            text-align: left;
            text-shadow: 0px 0px 0px rgba(2, 2, 2, 0.23);
            font-family: Montserrat;
            font-weight: 100;
            font-size: 32px;
            line-height: 36px
        }

        .pum-theme-28786 .pum-content,
        .pum-theme-hello-box .pum-content {
            color: #2d2d2d;
            font-family: inherit;
            font-weight: 100
        }

        .pum-theme-28786 .pum-content+.pum-close,
        .pum-theme-hello-box .pum-content+.pum-close {
            position: absolute;
            height: auto;
            width: auto;
            left: auto;
            right: -30px;
            bottom: auto;
            top: -30px;
            padding: 0px;
            color: #2d2d2d;
            font-family: Times New Roman;
            font-weight: 100;
            font-size: 32px;
            line-height: 28px;
            border: 1px none #ffffff;
            border-radius: 28px;
            box-shadow: 0px 0px 0px 0px rgba(2, 2, 2, 0.23);
            text-shadow: 0px 0px 0px rgba(0, 0, 0, 0.23);
            background-color: rgba(255, 255, 255, 1.00)
        }

        /* Popup Theme 28787: Cutting Edge */
        .pum-theme-28787,
        .pum-theme-cutting-edge {
            background-color: rgba(0, 0, 0, 0.50)
        }

        .pum-theme-28787 .pum-container,
        .pum-theme-cutting-edge .pum-container {
            padding: 18px;
            border-radius: 0px;
            border: 1px none #000000;
            box-shadow: 0px 10px 25px 0px rgba(2, 2, 2, 0.50);
            background-color: rgba(30, 115, 190, 1.00)
        }

        .pum-theme-28787 .pum-title,
        .pum-theme-cutting-edge .pum-title {
            color: #ffffff;
            text-align: left;
            text-shadow: 0px 0px 0px rgba(2, 2, 2, 0.23);
            font-family: Sans-Serif;
            font-weight: 100;
            font-size: 26px;
            line-height: 28px
        }

        .pum-theme-28787 .pum-content,
        .pum-theme-cutting-edge .pum-content {
            color: #ffffff;
            font-family: inherit;
            font-weight: 100
        }

        .pum-theme-28787 .pum-content+.pum-close,
        .pum-theme-cutting-edge .pum-content+.pum-close {
            position: absolute;
            height: 24px;
            width: 24px;
            left: auto;
            right: 0px;
            bottom: auto;
            top: 0px;
            padding: 0px;
            color: #1e73be;
            font-family: Times New Roman;
            font-weight: 100;
            font-size: 32px;
            line-height: 24px;
            border: 1px none #ffffff;
            border-radius: 0px;
            box-shadow: -1px 1px 1px 0px rgba(2, 2, 2, 0.10);
            text-shadow: -1px 1px 1px rgba(0, 0, 0, 0.10);
            background-color: rgba(238, 238, 34, 1.00)
        }

        /* Popup Theme 28788: Framed Border */
        .pum-theme-28788,
        .pum-theme-framed-border {
            background-color: rgba(255, 255, 255, 0.50)
        }

        .pum-theme-28788 .pum-container,
        .pum-theme-framed-border .pum-container {
            padding: 18px;
            border-radius: 0px;
            border: 20px outset #dd3333;
            box-shadow: 1px 1px 3px 0px rgba(2, 2, 2, 0.97) inset;
            background-color: rgba(255, 251, 239, 1.00)
        }

        .pum-theme-28788 .pum-title,
        .pum-theme-framed-border .pum-title {
            color: #000000;
            text-align: left;
            text-shadow: 0px 0px 0px rgba(2, 2, 2, 0.23);
            font-family: inherit;
            font-weight: 100;
            font-size: 32px;
            line-height: 36px
        }

        .pum-theme-28788 .pum-content,
        .pum-theme-framed-border .pum-content {
            color: #2d2d2d;
            font-family: inherit;
            font-weight: 100
        }

        .pum-theme-28788 .pum-content+.pum-close,
        .pum-theme-framed-border .pum-content+.pum-close {
            position: absolute;
            height: 20px;
            width: 20px;
            left: auto;
            right: -20px;
            bottom: auto;
            top: -20px;
            padding: 0px;
            color: #ffffff;
            font-family: Tahoma;
            font-weight: 700;
            font-size: 16px;
            line-height: 18px;
            border: 1px none #ffffff;
            border-radius: 0px;
            box-shadow: 0px 0px 0px 0px rgba(2, 2, 2, 0.23);
            text-shadow: 0px 0px 0px rgba(0, 0, 0, 0.23);
            background-color: rgba(0, 0, 0, 0.55)
        }

        /* Popup Theme 28789: Floating Bar - Soft Blue */
        .pum-theme-28789,
        .pum-theme-floating-bar {
            background-color: rgba(255, 255, 255, 0.00)
        }

        .pum-theme-28789 .pum-container,
        .pum-theme-floating-bar .pum-container {
            padding: 8px;
            border-radius: 0px;
            border: 1px none #000000;
            box-shadow: 1px 1px 3px 0px rgba(2, 2, 2, 0.23);
            background-color: rgba(238, 246, 252, 1.00)
        }

        .pum-theme-28789 .pum-title,
        .pum-theme-floating-bar .pum-title {
            color: #505050;
            text-align: left;
            text-shadow: 0px 0px 0px rgba(2, 2, 2, 0.23);
            font-family: inherit;
            font-weight: 400;
            font-size: 32px;
            line-height: 36px
        }

        .pum-theme-28789 .pum-content,
        .pum-theme-floating-bar .pum-content {
            color: #505050;
            font-family: inherit;
            font-weight: 400
        }

        .pum-theme-28789 .pum-content+.pum-close,
        .pum-theme-floating-bar .pum-content+.pum-close {
            position: absolute;
            height: 18px;
            width: 18px;
            left: auto;
            right: 5px;
            bottom: auto;
            top: 50%;
            padding: 0px;
            color: #505050;
            font-family: Sans-Serif;
            font-weight: 700;
            font-size: 15px;
            line-height: 18px;
            border: 1px solid #505050;
            border-radius: 15px;
            box-shadow: 0px 0px 0px 0px rgba(2, 2, 2, 0.00);
            text-shadow: 0px 0px 0px rgba(0, 0, 0, 0.00);
            background-color: rgba(255, 255, 255, 0.00);
            transform: translate(0, -50%)
        }

        /* Popup Theme 28790: Content Only - For use with page builders or block editor */
        .pum-theme-28790,
        .pum-theme-content-only {
            background-color: rgba(0, 0, 0, 0.70)
        }

        .pum-theme-28790 .pum-container,
        .pum-theme-content-only .pum-container {
            padding: 0px;
            border-radius: 0px;
            border: 1px none #000000;
            box-shadow: 0px 0px 0px 0px rgba(2, 2, 2, 0.00)
        }

        .pum-theme-28790 .pum-title,
        .pum-theme-content-only .pum-title {
            color: #000000;
            text-align: left;
            text-shadow: 0px 0px 0px rgba(2, 2, 2, 0.23);
            font-family: inherit;
            font-weight: 400;
            font-size: 32px;
            line-height: 36px
        }

        .pum-theme-28790 .pum-content,
        .pum-theme-content-only .pum-content {
            color: #8c8c8c;
            font-family: inherit;
            font-weight: 400
        }

        .pum-theme-28790 .pum-content+.pum-close,
        .pum-theme-content-only .pum-content+.pum-close {
            position: absolute;
            height: 18px;
            width: 18px;
            left: auto;
            right: 7px;
            bottom: auto;
            top: 7px;
            padding: 0px;
            color: #000000;
            font-family: inherit;
            font-weight: 700;
            font-size: 20px;
            line-height: 20px;
            border: 1px none #ffffff;
            border-radius: 15px;
            box-shadow: 0px 0px 0px 0px rgba(2, 2, 2, 0.00);
            text-shadow: 0px 0px 0px rgba(0, 0, 0, 0.00);
            background-color: rgba(255, 255, 255, 0.00)
        }

        #pum-28791 {
            z-index: 1999999999
        }

    </style>

    <style id="cky-style-inline">
        [data-cky-tag] {
            visibility: hidden;
        }

    </style>
    <style type="text/css">
        /* SJB Fonts */
        .sjb-page {
            font-family: "Roboto", sans-serif;
        }

        /* Job Filters Background Color */
        .sjb-page .sjb-filters {
            background-color: #f2f2f2;
        }

        /* Listing & Detail Page Title Color */
        .sjb-page .list-data .v1 .job-info h4 a,
        .sjb-page .list-data .v2 .job-info h4 a {
            color: #3b3a3c;
        }

        /* Job Detail Page Headings */
        .sjb-page .sjb-detail .list-data .v1 h3,
        .sjb-page .sjb-detail .list-data .v2 h3,
        .sjb-page .sjb-detail .list-data ul li::before,
        .sjb-page .sjb-detail .list-data .v1 .job-detail h3,
        .sjb-page .sjb-detail .list-data .v2 .job-detail h3,
        .sjb-page .sjb-archive-page .job-title,
        .sjb-page .job-features h3 {
            color: #3297fa;
        }

        /* Fontawesome Icon Color */
        .sjb-page .list-data .v1 .job-type i,
        .sjb-page .list-data .v1 .job-location i,
        .sjb-page .list-data .v1 .job-date i,
        .sjb-page .list-data .v2 .job-type i,
        .sjb-page .list-data .v2 .job-location i,
        .sjb-page .list-data .v2 .job-date i,
        .sjb-page .sjb-detail .list-data .v2 .job-features .sjb-title-value h4 i,
        .sjb-listing .list-data .v2 .job-features .sjb-title-value h4 i {
            color: #3b3a3c;
        }

        /* Fontawesome Text Color */
        .sjb-page .list-data .v1 .job-type,
        .sjb-page .list-data .v1 .job-location,
        .sjb-page .list-data .v1 .job-date,
        .sjb-page .list-data .v2 .job-type,
        .sjb-page .list-data .v2 .job-location,
        .sjb-page .list-data .v2 .job-date {
            color: #3297fa;
        }

        /* Job Filters-> All Buttons Background Color */
        .sjb-page .btn-primary,
        .sjb-page .btn-primary:hover,
        .sjb-page .btn-primary:active:hover,
        .sjb-page .btn-primary:active:focus,
        .sjb-page .sjb-detail .jobpost-form .file div,
        .sjb-page .sjb-detail .jobpost-form .file:hover div {
            background-color: #3297fa !important;
            color: #fff !important;
        }

        .sjb-page .sjb-listing a.sjb_view_more_btn,
        .sjb-page .sjb-listing a.sjb_view_less_btn {

            color: #3297fa !important;
        }

        /* Pagination Text Color */
        /* Pagination Background Color */
        .sjb-page .pagination li.list-item span.current,
        .sjb-page .pagination li.list-item a:hover,
        .sjb-page .pagination li.list-item span.current:hover {
            background: #164e91;
            border-color: #164e91;
            color: #fff;
        }

    </style>
    <link rel="icon" href="https://www.mutua.com.br/wp-content/uploads/2022/12/cropped-brasao_mutua-32x32.png" sizes="32x32" />
    <link rel="icon" href="https://www.mutua.com.br/wp-content/uploads/2022/12/cropped-brasao_mutua-192x192.png" sizes="192x192" />
    <link rel="apple-touch-icon" href="https://www.mutua.com.br/wp-content/uploads/2022/12/cropped-brasao_mutua-180x180.png" />
    <meta name="msapplication-TileImage" content="https://www.mutua.com.br/wp-content/uploads/2022/12/cropped-brasao_mutua-270x270.png" />
    <style type="text/css" id="wp-custom-css">
        .main-header .navbar-brand {
            margin-right: 100px !important;
        }

        .main-header .navbar .navbar-nav .nav-item .nav-link {
            padding: 0.625rem 0.625rem;
        }

        .main-header .navbar .navbar-nav .nav-item .nav-link[title="Acesso"] {
            margin-left: 5px;
        }

        .main-header .navbar .navbar-nav .nav-item .nav-link .material-icons-round {
            margin-right: 5px;
        }

        .slick-prev {
            width: 24px !important;
            height: 24px !important;
            margin-top: -10px;
            left: 10px !important;
            z-index: 10 !important;
            opacity: 1 !important;
            text-align: center !important;
        }

        .slick-next {
            width: 24px !important;
            height: 24px !important;
            margin-top: -10px;
            right: 10px !important;
            z-index: 10 !important;
            opacity: 1 !important;
            text-align: center !important;
        }

        .slick-prev:before,
        .slick-next:before {
            color: rgba(0, 0, 0, 0.4);
            font-size: 24px;
        }

        .widgetBotaoFlutuanteCarregado {
            width: 64px !important;
            height: 64px !important;
            position: relative;
        }

        .widgetBotaoFlutuanteCarregado:before {
            width: 50px;
            height: 50px;
            position: absolute;
            top: 7px;
            left: 7px;
            content: "";
            z-index: 2;
            background-image: url(https://www.mutua.com.br/wp-content/uploads/2023/02/logo_mutua.webp);
            background-repeat: no-repeat;
            background-position: center;
            background-size: 50px 50px;
            opacity: 1;
        }

        .widgetPrecisaDeAjuda {
            width: auto;
            height: 40px;
            padding: 0px 18px 0px 18px;
            background: #44ab3e;
            border-radius: 5px;
            position: fixed;
            right: 120px;
            bottom: 20px;
            z-index: 90;
            font-weight: 500;
            font-size: 14px;
            color: white;
            line-height: 40px;
        }

        .widgetPrecisaDeAjuda img.icone-chat {
            margin-right: 8px;
        }

        .widgetPrecisaDeAjuda:before {
            width: 30px;
            height: 30px;
            border-radius: 5px 5px 5px 20px;
            background: #44ab3e;
            position: fixed;
            right: 109px;
            bottom: 25px;
            z-index: 80;
            content: "";
            transform: rotate(45deg);
        }

        .widgetContakoAbrirIcone {
            width: 56px !important;
            height: 56px !important;
            opacity: 0;
        }

        .navbar .navbar-brand .img-fluid {
            width: auto;
            height: 42px;
        }

        .main-header .navbar .navbar-nav .nav-item.rounded>.nav-link {
            background: #00b5ff;
        }

        .main-header .navbar .navbar-nav .nav-item.rounded>.nav-link:hover {
            background: #3d6ea9;
        }

        .block__info-header .icon {
            width: 32px;
            height: 32px;
            font-size: 32px;
        }

        .s__simulation .btn-primary {
            background: #194385;
        }

        .s__blog ul li .nav-link .icon svg path {
            fill: #3d6ea9;
        }

        .s__blog .category {
            background: #3d6ea9;
        }

        .s__blog .category:hover {
            background: #00b5ff;
        }

        .s__social-banners .block__social {
            padding: 15px 20px !important;
        }

        .s__social-banners .block__social p span {
            font-size: 12px;
        }

        .s__app {
            display: none;
        }

        .s__system {
            display: none;
        }

        .s__video .btn-secondary {
            background: #194385;
            display: none !important;
        }

        .s__video .btn-secondary:hover {
            background: #00b5ff;
        }

        .gallery {
            margin-bottom: 20px;
        }

        .gallery figure {
            width: 30%;
            margin: 0px 0px 5px !important;
            display: inline-block;
        }

        .gallery figure img {
            aspect-ratio: 4/3;
            object-fit: cover;
            border-radius: 2px;
        }

        .gallery p.img-title {
            display: none;
        }

        .pagination .page-item:not(:last-child) {
            margin-right: 7px !important;
        }

        .main-header .navbar .navbar-nav .dropdown-menu {
            min-width: 300px;
            padding: 10px 10px 20px;
            border: 0;
            border-top-color: currentcolor;
            border-top-style: none;
            border-top-width: 0px;
            margin-top: 31px;
            box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.15);
        }

        .cky-consent-bar {
            padding: 15px !important;
            border-radius: 14px !important;
        }

        .cky-title {
            font-size: 16px !important;
        }

        .cky-notice-btn-wrapper p {
            font-size: 14px !important;
            line-height: 20px !important;
        }

        .cky-notice-btn-wrapper button {
            border-radius: 7px !important;
        }

        .sjb-page .sjb-listing .list-view .no-job-listing .no-job-listing-text {
            font-size: 36px;
            letter-spacing: 5px;
            display: none;
        }

        .sjb-page .no-job-listing img {
            width: 1040px;
        }

        .me-2 {
            margin-right: 0.5rem !important;
            display: none;
        }

        .s__simulation .form-range-custom {
            -webkit-appearance: none;
            width: 100%;
            height: 4px;
            background: rgb(20 66 136);
            background-image: linear-gradient(#003DDF, #003DDF);
            background-size: 0% 100%;
            background-repeat: no-repeat;
            transition: none;
        }

        .hentry .wp-caption p.wp-caption-text {
            line-height: 1.5;
            font-size: 14px;
            margin: 0;
        }

        /* categorias com links errados 0.0.0.17 */
        .s__blog .category {
            background: #3d6ea9;
            display: none;
        }

        .fs-10 {
            font-size: 10px;
            font-size: 0.625rem;
            display: none;
        }

        .page-template-page-jobs.page-id-30975 .s__h-page h1 {}

        .page-template-page-jobs.page-id-30975 .p__jobs.post-30975 .p__jobs--header {
            padding-top: 0px !important;
        }

        .page-template-page-jobs.page-id-30975 .p__jobs.post-30975 .p__jobs--header img {
            margin-bottom: 50px;
        }

        img[src="https://www.mutua.com.br/wp-content/uploads/2023/08/banner-oportunidades.webp"] {
            position: relative;
        }

        /* img[src="https://www.mutua.com.br/wp-content/uploads/2023/08/banner-oportunidades.webp"] :after {
	width: 100%;
	height: 300px;
	background: yellow;
	position: absolute;
	top: 0px;
	left: 0px;
	bottom: 0px;
	right: 0px;
	content: "";
	z-index: 10;
} */

    </style>

</head>
<body class="page-template page-template-templates page-template-page-benefits-req page-template-templatespage-benefits-req-php page page-id-30560 page-child parent-pageid-52 mutua essb-8.7">

    <h1 class="visually-hidden">MÚTUA - Caixa de Assistência dos Profissionais do Crea</h1>
    <header class="main-header">
        <div class="main-header__topbar bg-sec">

            <div class="container container-busca d-none">
                <div class="py-2">
                    <form role="search" method="get" class="block__search form-inline" action="https://www.mutua.com.br/">
                        <input type="search" class="search-field form-control" placeholder="O que você procura?" value="" name="s" title="Pesquisar por:" />
                        <button class="btn" type="submit">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                            </svg>
                        </button>
                    </form>
                </div>
            </div>

            <div class="container d-flex justify-content-between align-items-center">
                <!-- telefone / email -->
                <ul class="list-inline m-0">
                    <li class="list-inline-item me-2">
                        <a title="Ligue para nós!" href="tel:" class="d-flex align-items-center fs-13">
                            <span class="material-icons-round fs-18 me-2">call</span>
                            <span class="mask-0800 d-none d-md-block"></span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a title="Fale Conosco" href="mailto:atendimento@mutua.com.br?subject=Fale Conosco" class="d-flex align-items-center fs-13">
                            <span class="material-icons-round fs-18 me-2">mark_email_unread</span>
                            <span class="d-none d-md-block">Fale Conosco</span>
                        </a>
                    </li>
                </ul>

                <ul class="list-inline list-menu d-flex align-items-center m-0">

                    <!-- protocolo-eletronico -->
                    <li class="list-inline-item me-3 d-none d-md-inline-block">
                        <a target="_blank" href="https://ged.mutua.com.br/docflow/xhtml/docflow/external/login/auth.jsf" class="btn btn-rounded">Protocolo eletrônico</a>
                    </li>

                    <!-- acesso-a-informacao -->
                    <li class="list-inline-item me-3 d-none d-md-inline-block">
                        <a href="https://acessoainformacao.mutua.com.br/" target="_blank" class="d-flex align-items-center fs-13">
                            <span class="material-icons-round text-warning me-2">info</span>
                            Transparência
                        </a>
                    </li>

                    <!-- acessibilidade -->
                    <li class="list-inline-item">
                        <ul class="list-inline d-flex align-items-center">
                            <!-- <li class="list-inline-item me-2 color-qua d-none d-md-inline-block">
                    Acessibilidade
                  </li> -->
                            <li class="list-inline-item me-2 d-md-none">
                                <div class="dropdown">

                                    <button type="button" class="btn btn-circle more dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                        <span class="material-icons-round fs-18">more_horiz</span>
                                    </button>

                                    <ul class="dropdown-menu dropdown-menu-end">
                                        <li>
                                            <a href="https://ged.mutua.com.br/docflow/xhtml/docflow/external/login/auth.jsf" target="_blank" class="dropdown-item text-dark">
                                                Protocolo Eletrônico
                                            </a>
                                        </li>
                                        <li>
                                            <a href="https://acessoainformacao.mutua.com.br/" target="_blank" class="dropdown-item text-dark">
                                                Acesso à Informação
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>

                            <!-- <li class="list-inline-item me-2">
                    <a href="#" class="btn btn-circle"><span class="material-icons-round fs-18">accessibility</span></a>
                  </li> -->

                            <li class="list-inline-item">
                                <a href="#" id="botao-busca" class="btn btn-circle"><span class="material-icons-round fs-18">search</span></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        <div class="main-header__content bg-qui">
            <div class="container">
                <nav id="navbar" class="navbar navbar-expand-lg bsnav">
                    <button class="navbar-toggler toggler-spring"><span class="navbar-toggler-icon"></span></button>

                    <a class="navbar-brand me-auto me-lg-5 ms-2 ms-lg-0" href="{{route('index')}}" title="MÚTUA" rel="home">
                        <img width="400" height="100" src="https://www.mutua.com.br/wp-content/uploads/2022/12/logo_mutua.webp" class="img-fluid" alt="" decoding="async" srcset="https://www.mutua.com.br/wp-content/uploads/2022/12/logo_mutua.webp 400w, https://www.mutua.com.br/wp-content/uploads/2022/12/logo_mutua-300x75.webp 300w" sizes="(max-width: 400px) 100vw, 400px" />
                    </a>

                    <a class="btn btn-rounded d-md-none" title="Associe-se" href="/associe-se">
                        <span class="fs-18 me-1 material-icons-round">assignment_ind</span>Associe-se</a>
                    </li>

                    <div class="collapse navbar-collapse justify-content-md-center">
                        <ul id="menu-global" class="navbar-nav navbar-mobile w-100">
                            <li id="menu-item-63" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children nav-item menu-item-63 dropdown"><a class="nav-link dropdown-toggle" title="Quem somos" href="https://www.mutua.com.br/quem-somos/">Quem somos</a>
                                <ul role="menu" class="dropdown-menu">
                                    <li id="menu-item-89" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-89"><a class="nav-link" title="Diretoria Executiva" href="https://www.mutua.com.br/quem-somos/diretoria-executiva/">Diretoria Executiva</a></li>
                                    <li id="menu-item-90" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-90"><a class="nav-link" title="Diretorias Regionais" href="https://www.mutua.com.br/quem-somos/diretorias-regionais/">Diretorias Regionais</a></li>
                                    <li id="menu-item-91" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-91"><a class="nav-link" title="Quem é quem (Sede)" href="https://www.mutua.com.br/quem-somos/quem-e-quem-sede/">Quem é quem (Sede)</a></li>
                                    <li id="menu-item-92" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-92"><a class="nav-link" title="Quem é quem nos estados" href="https://www.mutua.com.br/quem-somos/quem-e-quem-nos-estados/">Quem é quem nos estados</a></li>
                                    <li id="menu-item-22101" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-22101"><a class="nav-link" title="Legislação" href="https://www.mutua.com.br/legislacao/">Legislação</a></li>
                                    <li id="menu-item-31565" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-31565"><a class="nav-link" title="Publicações" href="https://www.mutua.com.br/publicacoes/">Publicações</a></li>
                                </ul>
                            </li>
                            <li id="menu-item-7471" class="menu-item menu-item-type-post_type menu-item-object-page current-page-ancestor current-menu-ancestor current-menu-parent current-page-parent current_page_parent current_page_ancestor menu-item-has-children nav-item menu-item-7471 dropdown"><a class="nav-link dropdown-toggle" title="Benefícios" href="https://www.mutua.com.br/beneficios/">Benefícios</a>
                                <ul role="menu" class="dropdown-menu">
                                    <li id="menu-item-5115" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-5115"><a class="nav-link" title="Ajuda Mútua" href="https://www.mutua.com.br/beneficios/ajuda-mutua/">Ajuda Mútua</a></li>
                                    <li id="menu-item-5116" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-5116"><a class="nav-link" title="Equipa Bem" href="https://www.mutua.com.br/beneficios/equipa-bem/">Equipa Bem</a></li>
                                    <li id="menu-item-30579" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-30560 current_page_item nav-item menu-item-30579 active"><a class="nav-link" title="Mútua+Azul" href="https://www.mutua.com.br/beneficios/mutuamaisazul/">Mútua+Azul</a></li>
                                    <li id="menu-item-5117" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-5117"><a class="nav-link" title="Férias Mais" href="https://www.mutua.com.br/beneficios/ferias-mais/">Férias Mais</a></li>
                                    <li id="menu-item-5119" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-5119"><a class="nav-link" title="Garante Saúde" href="https://www.mutua.com.br/beneficios/garante-saude/">Garante Saúde</a></li>
                                    <li id="menu-item-5122" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-5122"><a class="nav-link" title="Simulador de benefícios" href="https://www.mutua.com.br/beneficios/simulador-de-beneficios/">Simulador de benefícios</a></li>
                                    <li id="menu-item-9963" class="menu-item menu-item-type-custom menu-item-object-custom nav-item menu-item-9963"><a class="nav-link" title="Classificação Rating" target="_blank" href="https://www.mutua.com.br/wp-content/uploads/2023/03/class_risco_cred_rev_01_28_03_23.pdf">Classificação Rating</a></li>
                                    <li id="menu-item-5118" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-5118"><a class="nav-link" title="Funeral" href="https://www.mutua.com.br/beneficios/funeral/">Funeral</a></li>
                                    <li id="menu-item-5120" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-5120"><a class="nav-link" title="Pecúlio por morte" href="https://www.mutua.com.br/beneficios/peculio/">Pecúlio por morte</a></li>
                                    <li id="menu-item-5121" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-5121"><a class="nav-link" title="Pecuniário" href="https://www.mutua.com.br/beneficios/pecuniario/">Pecuniário</a></li>
                                    <li id="menu-item-11211" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-11211"><a class="nav-link" title="Programa de Inclusão da Mútua – PIM" href="https://www.mutua.com.br/beneficios/programa-de-inclusao-da-mutua-pim/">Programa de Inclusão da Mútua – PIM</a></li>
                                    <li id="menu-item-29735" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-29735"><a class="nav-link" title="ABNT" href="https://www.mutua.com.br/abnt/">ABNT</a></li>
                                </ul>
                            </li>
                            <li id="menu-item-24362" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children nav-item menu-item-24362 dropdown"><a class="nav-link dropdown-toggle" title="Plano de Saúde" href="https://www.mutua.com.br/plano-de-saude/">Plano de Saúde</a>
                                <ul role="menu" class="dropdown-menu">
                                    <li id="menu-item-24363" class="menu-item menu-item-type-custom menu-item-object-custom nav-item menu-item-24363"><a class="nav-link" title="Seguros Unimed" target="_blank" href="https://saude.mutua.com.br/">Seguros Unimed</a></li>
                                    <li id="menu-item-24364" class="menu-item menu-item-type-custom menu-item-object-custom nav-item menu-item-24364"><a class="nav-link" title="Unimed Teresina" target="_blank" href="https://saude.mutua.com.br/teresina/">Unimed Teresina</a></li>
                                    <li id="menu-item-24365" class="menu-item menu-item-type-custom menu-item-object-custom nav-item menu-item-24365"><a class="nav-link" title="Qualicorp" target="_blank" href="https://qualicorpmutua.com.br/">Qualicorp</a></li>
                                    <li id="menu-item-29754" class="menu-item menu-item-type-custom menu-item-object-custom nav-item menu-item-29754"><a class="nav-link" title="Extramed - Planos RS" target="_blank" href="https://www.extramed.com.br/entidade/index.php?id=MUTUARS">Extramed &#8211; Planos RS</a></li>
                                    <li id="menu-item-29755" class="menu-item menu-item-type-custom menu-item-object-custom nav-item menu-item-29755"><a class="nav-link" title="Extramed - Planos SC" target="_blank" href="https://www.extramed.com.br/entidade/index.php?id=MUTUASC">Extramed &#8211; Planos SC</a></li>
                                    <li id="menu-item-29756" class="menu-item menu-item-type-custom menu-item-object-custom nav-item menu-item-29756"><a class="nav-link" title="Extramed - Planos PR" target="_blank" href="https://www.extramed.com.br/entidade/index.php?id=MUTUAPR">Extramed &#8211; Planos PR</a></li>
                                    <li id="menu-item-29759" class="menu-item menu-item-type-custom menu-item-object-custom nav-item menu-item-29759"><a class="nav-link" title="Benevix" href="https://www.benevix.com.br/">Benevix</a></li>
                                </ul>
                            </li>
                            <li id="menu-item-28608" class="menu-item menu-item-type-custom menu-item-object-custom nav-item menu-item-28608"><a class="nav-link" title="Previdência" target="_blank" href="https://www.tecnoprev.com.br/">Previdência</a></li>
                            <li id="menu-item-30700" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-30700"><a class="nav-link" title="Divulga Mútua" href="https://www.mutua.com.br/divulga-mutua/">Divulga Mútua</a></li>
                            <li id="menu-item-29728" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-29728"><a class="nav-link" title="ABNT" href="https://www.mutua.com.br/abnt/">ABNT</a></li>
                            <li id="menu-item-24240" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-24240"><a class="nav-link" title="LGPD" href="https://www.mutua.com.br/lgpd/">LGPD</a></li>
                            <li id="menu-item-65" class="rounded ms-auto menu-item menu-item-type-custom menu-item-object-custom nav-item menu-item-65"><a class="nav-link" title="Associe-se" href="/associe-se"><span class="material-icons-round">assignment_ind</span>Associe-se</a></li>
                            <li id="menu-item-66" class="rounded rounded-sec nav-access menu-item menu-item-type-custom menu-item-object-custom nav-item menu-item-66"><a class="nav-link" title="Acesso" target="_blank" href="{{route('login')}}"><span class="material-icons-round">lock</span>Acesso</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    <div class="bsnav-mobile">
        <div class="bsnav-mobile-overlay"></div>
        <div class="navbar justify-content-start"></div>
    </div>
    <main id="content" role="main">
        <section>
            <div class="s__h-page py-5 color-qua">
                <div class="container text-center">
                    <h1>@yield('apresentacao')</h1>
                </div>
            </div>
            <article class="p__beneficios post-30560 page type-page status-publish hentry">
                <div class="container mb-5">
                    <div class="row">





                        @yield('content')


                    </div>
                </div>

                </div>
                </div>
            </article>
        </section>
    </main>
    <footer class="main-footer" role="contentinfo">
        <div class="main-footer__links">
            <div class="container">
                <ul id="menu-termos-de-uso" class="navbar-nav flex-row justify-content-md-end">
                    <li id="menu-item-114" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-114"><a class="nav-link" title="Termos de Uso" href="https://www.mutua.com.br/termos-de-uso/">Termos de Uso</a></li>
                    <li id="menu-item-7538" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-7538"><a class="nav-link" title="Ouvidoria" href="https://www.mutua.com.br/ouvidoria/">Ouvidoria</a></li>
                    <li id="menu-item-7485" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-privacy-policy nav-item menu-item-7485"><a class="nav-link" title="Política de Privacidade" href="https://www.mutua.com.br/politica-de-privacidade/">Política de Privacidade</a></li>
                    <li id="menu-item-8116" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-8116"><a class="nav-link" title="Política de Cookies" href="https://www.mutua.com.br/politica-de-cookies/">Política de Cookies</a></li>
                    <li id="menu-item-17419" class="menu-item menu-item-type-custom menu-item-object-custom nav-item menu-item-17419"><a class="nav-link" title="Estatuto" target="_blank" href="https://www.mutua.com.br/wp-content/uploads/2023/03/estatuto_21_06_2021.pdf">Estatuto</a></li>
                    <li id="menu-item-17420" class="menu-item menu-item-type-custom menu-item-object-custom nav-item menu-item-17420"><a class="nav-link" title="Lei 6496" target="_blank" href="https://www.mutua.com.br/wp-content/uploads/2023/03/lei_6496_1977_21_06_2021.pdf">Lei 6496</a></li>
                    <li id="menu-item-31566" class="menu-item menu-item-type-post_type menu-item-object-page nav-item menu-item-31566"><a class="nav-link" title="Publicações" href="https://www.mutua.com.br/publicacoes/">Publicações</a></li>
                </ul>
            </div>
        </div>
        <div class="main-footer__content">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 color-qua text-center text-md-start">
                        <a class="logo d-inline-block mb-4 mb-md-5" href="https://www.mutua.com.br/" title="MÚTUA" rel="home">
                            <img width="400" height="100" src="https://www.mutua.com.br/wp-content/uploads/2022/12/logo_mutua_light.webp" class="img-fluid" alt="" decoding="async" loading="lazy" srcset="https://www.mutua.com.br/wp-content/uploads/2022/12/logo_mutua_light.webp 400w, https://www.mutua.com.br/wp-content/uploads/2022/12/logo_mutua_light-300x75.webp 300w" sizes="(max-width: 400px) 100vw, 400px" /> </a>

                        <p class="title font-medium mb-4 d-none d-md-block">Caixa de Assistência dos Profissionais do Crea</p>

                        <p class="fs-14 d-none d-md-block">SHN Q. 4 BL C - Asa Norte, Brasília - DF,<br />
                            70704-902, Brasil</p>
                    </div>

                    <div class="col-md-8 offset-md-1">
                        <div class="row mb-5">
                            <div class="col-md-6 mb-2 mb-md-0">
                                <div class="card">
                                    <span class="card-title">Contato</span>
                                    <div class="card-content">
                                        <ul class="list-unstyled">
                                            <li>
                                                <a title="Ligue para nós!" href="tel:(61) 3348-0200"><span class="material-icons-round color-ter fs-14 me-2">perm_phone_msg</span><span class="">(61) 3348-0200</span></a>
                                            </li>
                                            <li>
                                                <a title="Ligue para nós!" href="tel:"><span class="material-icons-round color-ter fs-14 me-2">add_ic_call</span><span class="mask-0800"></span></a>
                                            </li>
                                            <li>
                                                <a href="mailto:atendimento@mutua.com.br?subject=Fale Conosco" title="Fale Conosco"><span class="material-icons-round color-ter fs-18 me-2">markunread</span>atendimento@mutua.com.br</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card">
                                    <span class="card-title">Social</span>

                                    <div class="card-content">
                                        <ul class="social-networks list-inline">
                                            <li class="list-inline-item me-1">
                                                <a href="https://pt-br.facebook.com/MutuadeAssistencia/" target="_blank">
                                                    <img src="https://www.mutua.com.br/wp-content/uploads/2023/02/facebook.svg" width="40" height="40" alt="Icone">
                                                </a>
                                            </li>
                                            <li class="list-inline-item me-1">
                                                <a href="https://www.instagram.com/mutuadeassistencia/" target="_blank">
                                                    <img src="https://www.mutua.com.br/wp-content/uploads/2022/08/instagram.svg" width="40" height="40" alt="Icone">
                                                </a>
                                            </li>
                                            <li class="list-inline-item me-1">
                                                <a href="https://twitter.com/comunicamutua" target="_blank">
                                                    <img src="https://www.mutua.com.br/wp-content/uploads/2022/08/twitter.svg" width="40" height="40" alt="Icone">
                                                </a>
                                            </li>
                                            <li class="list-inline-item me-1">
                                                <a href="https://br.linkedin.com/company/mutuadeassistencia" target="_blank">
                                                    <img src="https://www.mutua.com.br/wp-content/uploads/2022/08/linkedin.svg" width="40" height="40" alt="Icone">
                                                </a>
                                            </li>
                                            <li class="list-inline-item me-1">
                                                <a href="https://www.youtube.com/c/TVM%C3%BAtua" target="_blank">
                                                    <img src="https://www.mutua.com.br/wp-content/uploads/2022/08/youtube.svg" width="40" height="40" alt="Icone">
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <aside class="sidebar-footer row">
                            <div class="widget col-md-3 mb-3 mb-md-5 widget_nav_menu" id="nav_menu-2">
                                <p class="fs-14 text-uppercase color-qua mb-4"><strong class="font-semi">Benefícios</strong></button></p>
                                <div class="menu-beneficios-container">
                                    <ul id="menu-beneficios" class="menu">
                                        <li id="menu-item-228" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-228"><a href="https://www.mutua.com.br/beneficios/ajuda-mutua/">Ajuda Mútua</a></li>
                                        <li id="menu-item-229" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-229"><a href="https://www.mutua.com.br/beneficios/equipa-bem/">Equipa Bem</a></li>
                                        <li id="menu-item-30578" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-30560 current_page_item menu-item-30578"><a href="https://www.mutua.com.br/beneficios/mutuamaisazul/" aria-current="page">Mútua+Azul</a></li>
                                        <li id="menu-item-230" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-230"><a href="https://www.mutua.com.br/beneficios/ferias-mais/">Férias Mais</a></li>
                                        <li id="menu-item-232" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-232"><a href="https://www.mutua.com.br/beneficios/garante-saude/">Garante Saúde</a></li>
                                        <li id="menu-item-235" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-235"><a href="https://www.mutua.com.br/beneficios/simulador-de-beneficios/">Simulador de benefícios</a></li>
                                        <li id="menu-item-237" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-237"><a target="_blank" rel="noopener" href="https://www.mutua.com.br/wp-content/uploads/2023/03/class_risco_cred_rev_01_28_03_23.pdf">Classificação Rating</a></li>
                                        <li id="menu-item-231" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-231"><a href="https://www.mutua.com.br/beneficios/funeral/">Funeral</a></li>
                                        <li id="menu-item-233" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-233"><a href="https://www.mutua.com.br/beneficios/peculio/">Pecúlio por morte</a></li>
                                        <li id="menu-item-234" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-234"><a href="https://www.mutua.com.br/beneficios/pecuniario/">Pecuniário</a></li>
                                        <li id="menu-item-11212" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11212"><a href="https://www.mutua.com.br/beneficios/programa-de-inclusao-da-mutua-pim/">Programa de Inclusão da Mútua – PIM</a></li>
                                        <li id="menu-item-236" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-236"><a target="_blank" rel="noopener" href="https://www.tecnoprev.com.br/">Previdência Complementar</a></li>
                                        <li id="menu-item-29729" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-29729"><a href="https://www.mutua.com.br/abnt/">ABNT</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="widget col-md-3 mb-3 mb-md-5 widget_nav_menu" id="nav_menu-3">
                                <p class="fs-14 text-uppercase color-qua mb-4"><strong class="font-semi">Acesso à Informação</strong></button></p>
                                <div class="menu-transparencia-container">
                                    <ul id="menu-transparencia" class="menu">
                                        <li id="menu-item-253" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-253"><a href="https://www.mutua.com.br/lgpd/">LGPD</a></li>
                                        <li id="menu-item-254" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-254"><a href="https://ged.mutua.com.br/docflow/xhtml/docflow/external/login/auth.jsf">Protocolo Eletrônico</a></li>
                                        <li id="menu-item-13754" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-13754"><a target="_blank" rel="noopener" href="https://www.mutua.com.br/wp-content/uploads/2023/08/cod_etica_rev02.pdf">Código de ética</a></li>
                                        <li id="menu-item-30816" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-30816"><a target="_blank" rel="noopener" href="http://intranet.mutua.com.br/joomla_login.php?tipoLogin=F">Intranet</a></li>
                                        <li id="menu-item-30822" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-30822"><a target="_blank" rel="noopener" href="https://signersite.mutua.com.br/">Mútua Signer</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="widget col-md-3 mb-3 mb-md-5 widget_nav_menu" id="nav_menu-4">
                                <p class="fs-14 text-uppercase color-qua mb-4"><strong class="font-semi">Quem Somos</strong></button></p>
                                <div class="menu-quem-somos-container">
                                    <ul id="menu-quem-somos" class="menu">
                                        <li id="menu-item-7734" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7734"><a href="https://www.mutua.com.br/quem-somos/">Quem somos</a></li>
                                        <li id="menu-item-257" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-257"><a href="https://www.mutua.com.br/quem-somos/diretoria-executiva/">Diretoria Executiva</a></li>
                                        <li id="menu-item-258" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-258"><a href="https://www.mutua.com.br/quem-somos/diretorias-regionais/">Diretorias Regionais</a></li>
                                        <li id="menu-item-259" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-259"><a href="https://www.mutua.com.br/quem-somos/quem-e-quem-sede/">Quem é quem (Sede)</a></li>
                                        <li id="menu-item-260" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-260"><a href="https://www.mutua.com.br/quem-somos/quem-e-quem-nos-estados/">Quem é quem (Estados)</a></li>
                                        <li id="menu-item-22102" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22102"><a href="https://www.mutua.com.br/legislacao/">Legislação</a></li>
                                        <li id="menu-item-9953" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-9953"><a target="_blank" rel="noopener" href="https://blog.mutua.com.br/">Nosso blog</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="widget col-md-3 mb-3 mb-md-5 widget_nav_menu" id="nav_menu-5">
                                <p class="fs-14 text-uppercase color-qua mb-4"><strong class="font-semi">Redes</strong></button></p>
                                <div class="menu-redes-container">
                                    <ul id="menu-redes" class="menu">
                                        <li id="menu-item-264" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-264"><a target="_blank" rel="noopener" href="https://pt-br.facebook.com/MutuadeAssistencia/">Facebook</a></li>
                                        <li id="menu-item-265" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-265"><a target="_blank" rel="noopener" href="https://www.instagram.com/mutuadeassistencia/">Instagram</a></li>
                                        <li id="menu-item-266" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-266"><a target="_blank" rel="noopener" href="https://twitter.com/comunicamutua">Twitter</a></li>
                                        <li id="menu-item-267" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-267"><a target="_blank" rel="noopener" href="https://www.youtube.com/TVMUTUA">Youtube</a></li>
                                        <li id="menu-item-268" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-268"><a target="_blank" rel="noopener" href="https://br.linkedin.com/company/mutuadeassistencia">Linkedin</a></li>
                                    </ul>
                                </div>
                            </div>
                        </aside>
                        <div class="row mb-5">
                            <div class="col-12">
                                <ul class="list-inline">
                                    <li class="list-inline-item me-1 me-md-4">
                                        <a href="https://www.mutua.com.br/trabalhe-conosco" target="_self" class="btn btn-outline btn-outline-white d-inline-flex align-items-center px-3 px-md-4"><span class="material-icons-round fs-16 me-2">business_center</span>Trabalhe Conosco</a>
                                    </li>
                                    <li class="list-inline-item me-1 me-md-4">
                                        <a href="http://intranet.mutua.com.br/joomla_login.php?tipoLogin=F" target="_blank" class="btn btn-outline btn-outline-white d-inline-flex align-items-center px-3 px-md-4"><span class="material-icons-round fs-16 me-2">devices</span>Acessar Intranet</a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="https://outlook.office.com/" target="_blank" class="btn btn-outline btn-outline-white d-inline-flex align-items-center px-3 px-md-4"><span class="material-icons-round fs-16 me-2">alternate_email</span>Acessar Webmail</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container">
                <div class="location position-relative">

                    <div class="acf-address">
                        <p class="name color-sex fs-20 font-semi mb-2">Mútua - Caixa de Assistência dos Profissionais do Crea</p>
                        <p class="mb-4">SHN Q. 4 BL C - Asa Norte, Brasília - DF, 70704-902</p>
                        <a href="https://goo.gl/maps/8ncXpwYUTrWcDimK9" class="btn btn-secondary d-inline-flex align-items-center" target="_blank">
                            <span class="material-icons-round me-2">assistant_direction</span>Como chegar
                        </a>
                    </div>

                    <!-- <div class="acf-map"> -->
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3839.2816430243233!2d-47.89151168457376!3d-15.789096527032346!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x935a3bca658b8019%3A0xd14c94accfa90d20!2sM%C3%BAtua%20-%20Caixa%20de%20Assist%C3%AAncia%20dos%20Profissionais%20do%20Crea!5e0!3m2!1spt-BR!2sbr!4v1677869610184!5m2!1spt-BR!2sbr" style="width: calc(100% - 380px); float: right; height: 210px; border: 0px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                    <!-- </div> -->

                </div>
            </div>


            <div class="main-footer__copy">
                <div class="container text-center">
                    <img src="https://www.mutua.com.br/wp-content/themes/mutua/assets/images/logo-sistema-mutua.webp" alt="MÚTUA" class="mb-5" style="width: auto; height: 30px;">
                    <p class="fs-14 color-qua m-0 d-none">A Mútua – Caixa de Assistência dos Profissionais dos Creas – é uma sociedade civil sem fins lucrativos criada pelo Conselho Federal de Engenharia e Agronomia (Confea), pela resolução nº 252 de 17 de dezembro de 1977, conforme autorização legal contida no artigo 4º da Lei 6.496 de 7 de dezembro de 1977.</p>
                </div>

                <div class="container text-center py-4">
                    <p class="fs-14 m-0 color-qua">Todos direitos reservados à <strong>MÚTUA | Caixa de Assistência dos Profissionais do Crea</strong> - 2023</p>
                </div>
            </div>
    </footer>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDq7hkuyhSM_e-17tmVAzBybhaAc8SzD1o&callback=Function.prototype"></script>

    <script type='text/javascript' src='https://www.mutua.com.br/wp-content/plugins/contact-form-7/includes/swv/js/index.js?ver=5.8' id='swv-js'></script>
    <script type='text/javascript' id='contact-form-7-js-extra'>
        /* <![CDATA[ */
        var wpcf7 = {
            "api": {
                "root": "https:\/\/www.mutua.com.br\/wp-json\/"
                , "namespace": "contact-form-7\/v1"
            }
        };
        /* ]]> */

    </script>
    <script type='text/javascript' src='https://www.mutua.com.br/wp-content/plugins/contact-form-7/includes/js/index.js?ver=5.8' id='contact-form-7-js'></script>
    <script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js?ver=1.1.0' id='wp-mutua-associados-popper-js'></script>
    <script type='text/javascript' src='//stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js?ver=1.1.0' id='wp-mutua-associados-bootstrap-js'></script>
    <script type='text/javascript' src='https://www.mutua.com.br/wp-includes/js/jquery/ui/core.min.js?ver=1.13.2' id='jquery-ui-core-js'></script>
    <script type='text/javascript' src='https://www.mutua.com.br/wp-includes/js/jquery/ui/datepicker.min.js?ver=1.13.2' id='jquery-ui-datepicker-js'></script>
    <script id="jquery-ui-datepicker-js-after" type="text/javascript">
        jQuery(function(jQuery) {
            jQuery.datepicker.setDefaults({
                "closeText": "Fechar"
                , "currentText": "Hoje"
                , "monthNames": ["janeiro", "fevereiro", "mar\u00e7o", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"]
                , "monthNamesShort": ["jan", "fev", "mar", "abr", "maio", "jun", "jul", "ago", "set", "out", "nov", "dez"]
                , "nextText": "Seguinte"
                , "prevText": "Anterior"
                , "dayNames": ["domingo", "segunda-feira", "ter\u00e7a-feira", "quarta-feira", "quinta-feira", "sexta-feira", "s\u00e1bado"]
                , "dayNamesShort": ["dom", "seg", "ter", "qua", "qui", "sex", "s\u00e1b"]
                , "dayNamesMin": ["D", "S", "T", "Q", "Q", "S", "S"]
                , "dateFormat": "MM d, yy"
                , "firstDay": 1
                , "isRTL": false
            });
        });

    </script>
    <script type='text/javascript' src='https://www.mutua.com.br/wp-content/plugins/wp-mutua-associado/public/js/wp-mutua-associados-public.js?ver=6.3.1' id='ajaxHandle-js'></script>
    <script type='text/javascript' src='https://www.mutua.com.br/wp-content/plugins/easy-social-share-buttons3/assets/modules/pinterest-pro.min.js?ver=8.7' id='pinterest-pro-js-js'></script>
    <script type='text/javascript' src='https://www.mutua.com.br/wp-content/plugins/easy-social-share-buttons3/assets/modules/subscribe-forms.min.js?ver=8.7' id='subscribe-forms-js-js'></script>
    <script type='text/javascript' src='https://www.mutua.com.br/wp-content/plugins/easy-social-share-buttons3/assets/js/essb-core.min.js?ver=8.7' id='easy-social-share-buttons-core-js'></script>
    <script id="easy-social-share-buttons-core-js-after" type="text/javascript">
        var essb_settings = {
            "ajax_url": "https:\/\/www.mutua.com.br\/wp-admin\/admin-ajax.php"
            , "essb3_nonce": "e92cd07a82"
            , "essb3_plugin_url": "https:\/\/www.mutua.com.br\/wp-content\/plugins\/easy-social-share-buttons3"
            , "essb3_stats": false
            , "essb3_ga": false
            , "essb3_ga_ntg": false
            , "blog_url": "https:\/\/www.mutua.com.br\/"
            , "post_id": "30560"
        };

    </script>
    <script type='text/javascript' id='popup-maker-site-js-extra'>
        /* <![CDATA[ */
        var pum_vars = {
            "version": "1.18.2"
            , "pm_dir_url": "https:\/\/www.mutua.com.br\/wp-content\/plugins\/popup-maker\/"
            , "ajaxurl": "https:\/\/www.mutua.com.br\/wp-admin\/admin-ajax.php"
            , "restapi": "https:\/\/www.mutua.com.br\/wp-json\/pum\/v1"
            , "rest_nonce": null
            , "default_theme": "28784"
            , "debug_mode": ""
            , "disable_tracking": ""
            , "home_url": "\/"
            , "message_position": "top"
            , "core_sub_forms_enabled": "1"
            , "popups": []
            , "cookie_domain": ""
            , "analytics_route": "analytics"
            , "analytics_api": "https:\/\/www.mutua.com.br\/wp-json\/pum\/v1"
        };
        var pum_sub_vars = {
            "ajaxurl": "https:\/\/www.mutua.com.br\/wp-admin\/admin-ajax.php"
            , "message_position": "top"
        };
        var pum_popups = {
            "pum-28791": {
                "triggers": [{
                    "type": "click_open"
                    , "settings": {
                        "cookie_name": ""
                        , "extra_selectors": ".popup"
                    }
                }]
                , "cookies": []
                , "disable_on_mobile": false
                , "disable_on_tablet": false
                , "atc_promotion": null
                , "explain": null
                , "type_section": null
                , "theme_id": "28784"
                , "size": "small"
                , "responsive_min_width": "0%"
                , "responsive_max_width": "100%"
                , "custom_width": "640px"
                , "custom_height_auto": false
                , "custom_height": "380px"
                , "scrollable_content": false
                , "animation_type": "fade"
                , "animation_speed": "350"
                , "animation_origin": "center top"
                , "open_sound": "none"
                , "custom_sound": ""
                , "location": "center"
                , "position_top": "100"
                , "position_bottom": "0"
                , "position_left": "0"
                , "position_right": "0"
                , "position_from_trigger": false
                , "position_fixed": false
                , "overlay_disabled": false
                , "stackable": false
                , "disable_reposition": false
                , "zindex": "1999999999"
                , "close_button_delay": "0"
                , "fi_promotion": null
                , "close_on_form_submission": false
                , "close_on_form_submission_delay": "0"
                , "close_on_overlay_click": false
                , "close_on_esc_press": false
                , "close_on_f4_press": false
                , "disable_form_reopen": false
                , "disable_accessibility": false
                , "theme_slug": "lightbox"
                , "id": 28791
                , "slug": "finalidade-pim"
            }
        };
        /* ]]> */

    </script>
    <script type='text/javascript' src='https://www.mutua.com.br/wp-content/plugins/popup-maker/assets/js/site.min.js?defer&#038;ver=1.18.2' id='popup-maker-site-js'></script>
    <script type="text/javascript"></script>




    <div class="none">
        <script>
            var botmanWidget = {
                aboutText: 'Start the conversation with Hi'
                , introMessage: "WELCOME TO ALL ABOUT LARAVEL"
            };

        </script>

        <script src='https://cdn.jsdelivr.net/npm/botman-web-widget@0/build/js/widget.js'></script>
    </div>

</body>
</html>
